/*----------------------------------------------------------------------------------------
-- FILE NAME        : uninstall_encryption.sql
-- Generated By     : Ex!lant Technologies Pvt Ltd.
-- Description      : Generic Error Logging utility
-- Date             : May 18, 2012
-- Author           : Ex!lant Development Team
-- Modification History:
------------------------------------------------------------------------------------------
--      When            Who                     What
------------------------------------------------------------------------------------------
--      18/05/2012      Ex! Dev Team            Initial Version
----------------------------------------------------------------------------------------*/

--Please don't forget to take backup of data if any , including error_log table.

SET HEAD ON PAGES 300 LINES 3000 FEEDBACK ON

DROP PUBLIC SYNONYM ex_crypto;
DROP PACKAGE ex_crypto;
DROP PUBLIC SYNONYM error_log;
DROP TABLE error_log;
DROP PUBLIC SYNONYM error_seq;
DROP SEQUENCE error_seq;
DROP PUBLIC SYNONYM p_log_error;
DROP PROCEDURE p_log_error;
DROP TABLE encryption_example;
